const mongoose = require('mongoose');

const town_schema = new mongoose.Schema({
        // district_name : String,
        // town_name: String,
        // total_households: Number,
        // total_population_of_town : Number,
        // total_male_population_of_town: Number,
        // total_female_population_of_town: Number,
        // hospital_allopathic : Number,
        // hospital_allopathic_bed: Number,
        // hospital_allopathic_doctors_total_strength: Number,
        // hospital_allopathic_doctors_in_position : Number,
        // hospital_allopathic_para_medical_staff_total_strength: Number,
        // hospital_alternative_medicine: Number,
        // hospital_alternative_medicine_beds :Number,
        // hospital_alternative_medicine_doctors_total_strength: Number,
        // hospital_alternative_medicine_doctors_in_position : Number,
        // hospital_alternative_medicine_para_medical_staff_total_strength : Number,
        // hospital_alternative_medicine_nearest_facility : Number,
        // dispensary_health_centre : Number,
        // dispensary_health_centre_beds : Number,
        // dispensary_health_centre_doctors : Number,
        // dispensary_health_centre_doctors_in_position : Number,
        // dispensary_health_centre_para_medical_staff_in_position: Number,          
        // dispensary_health_centre_nearest_facility_distance : Number,
        // family_welfare_centre : Number,
        // family_welfare_centre_beds : Number,
        // family_welfare_centre_doctors_total_strength : Number,
        // family_welfare_centre_doctors_para_medical_staff_total_strength : Number,
        // family_welfare_centre_doctors_para_medical_staff_in_position : Number,
        // family_welfare_centre_nearest_facility : Number,
        // maternity_and_child_welfare_centre : Number,
        // maternity_and_child_welfare_centre_beds : Number,
        // maternity_and_child_welfare_centre_doctors_in_position : Number,
        // maternity_and_child_welfare_centre_para_medical_staff_total_strength : Number,
        // maternity_and_child_welfare_centre_para_medical_staff_in_position : Number,
        // maternity_and_child_welfare_centre_nearest_facility_centre : Number,
        // maternity_home : Number,
        // maternity_home_doctors_total_strength : Number,
        // maternity_home_doctors_in_position : Number,
        // maternity_home_para_medical_staff_total_strength : Number,
        // maternity_home_para_medical_staff_in_position : Number,
        // maternity_home_nearest_facility_distance : Number,
        // tb_hospital_clinic_beds: Number,
        // tb_hospital_clinic_doctors_total_strength : Number,
        // tb_hospital_clinic_doctors_in_position : Number,
        // tb_hospital_clinic_para_medical_staff_total_strength : Number,
        // tb_hospital_clinic_para_medical_staff_in_position : Number,
        // nursing_home : Number,
        // nursing_home_beds : Number,
        // nursing_home_doctors_total_strength : Number,
        // nursing_home_doctors_in_position : Number,
        // nursing_home_para_medical_staff_total_strength : Number,
        // nursing_home_nearest_facility_distance : Number,
        // veterinary_hospital : Number,
        // veterinary_hospital_beds : Number,
        // veterinary_hospital_doctors_total_strength : Number,
        // veterinary_hospital_doctors_in_position : Number,
        // veterinary_hospital_para_medical_staff_in_position : Number,
        // veterinary_hospital_nearest_facility_distance : Number,
        // mobile_health_clinic : Number,
        // mobile_health_clinic_beds : Number,
        // mobile_health_clinic_doctors_total_strength : Number,
        // mobile_health_clinic_para_medical_staff_total_strength : Number,
        // mobile_health_clinic_para_medical_staff_in_position : Number,
        // mobile_health_clinic_nearest_facility_distance : Number,
        // others : Number,
        // others_beds: Number,
        // others_doctors_total_strength : Number,
        // others_doctors_in_position : Number,
        // others_para_medical_staff_total_strength : Number,
        // others_para_medical_staff_in_position : Number,
        // others_nearest_facility_distance : Number,
        // non_government_in_and_out_patient : Number,
        // non_government_medicine_shop : Number,
        town_name: String,
        district_name: String,
        state_name: String,
        latitude:Number,
        longitude:Number,
        dt_code:Number,
        st_code:Number,
        'District Name': String,
        'Town Name':String,
        'Total   Households': Number,
        'Total Population of Town':Number,
        'Total Male Population of Town':Number,
        'Total Female Population of Town':Number,
        'Hospital Allopathic (Numbers)':Number,
        'Hospital Allopathic Beds (Numbers)':Number,
        'Hospital Allopathic Doctors-Total Strength (Numbers)':Number,
        'Hospital Allopathic Doctors-In Position (Numbers)':Number,
        'Hospital Allopathic Para Medical Staff-Total Strength (Numbers)':Number,
        'Hospital Allopathic Para Medical Staff-In Postion (Numbers)':Number,
        'Hospital Allopathic Nearest facility Distance (in Kms.)':Number,
        'Hospital Alternative Medicine (Numbers)':Number,
        'Hospital Alternative Medicine Beds (Numbers)':Number,
        'Hospital Alternative Medicine Doctors-Total Strength (Numbers)' :Number,
        'Hospital Alternative Medicine Doctors-In Position (Numbers)':Number,
        'Hospital Alternative Medicine Para Medical Staff-Total Strength (Numbers)':Number,
        'Hospital Alternative Medicine Para Medical Staff-In Position (Numbers)':Number,
        'Hospital Alternative Medicine Nearest facility Distance(in kms.)':Number,
        'Dispensary/Health Centre (Numbers)':Number,
        'Dispensary/Health Centre Beds (Numbers)':Number,
        'Dispensary/Health Centre Doctors-Total Strength (Numbers)':Number,
        'Dispensary/Health Centre Doctors-In Position (Numbers)':Number,
        'Dispensary/Health Centre Para Medical Staff-Total Strength (Numbers)':Number,
        'Dispensary/Health Centre Para Medical Staff-In Position (Numbers)':Number,
        'Dispensary/Health Centre Nearest facility Distance (in Kms.)':Number,
        'Family Welfare Centre (Numbers)':Number,
        'Family Welfare Centre Beds (Numbers)':Number,
        'Family Welfare Centre Doctors-Total Strength (Numbers)':Number,
        'Family Welfare Centre Doctors-In Position (Numbers)':Number,
        'Family Welfare Centre Doctors Para Medical Staff-Total Strength (Numbers)':Number,
        'Family Welfare Centre Para Medical Staff-In Position (Numbers)':Number,
        'Family Welfare Centre Nearest facility Distance (in kms.)':Number,
        'Maternity and Child Welfare Centre (Numbers)':Number,
        'Maternity and Child Welfare Centre Beds (Numbers)':Number,
        'Maternity and Child Welfare Centre Doctors-Total Strength (Numbers)':Number,
        'Maternity and Child Welfare Centre Doctors-In Position (Numbers)':Number,
        'Maternity and Child Welfare Centre Para Medical Staff-Total Strength (Numbers)':Number,
        'Maternity and Child Welfare Centre Para Medical Staff-In Position (Numbers)': Number,
        'Maternity and Child Welfare Centre Nearest facility Distance (in Kms.)':Number,
        'Maternity Home (Numbers)':Number,
        'Maternity Home Beds (Numbers)':Number,
        'Maternity Home Doctors-Total Strength (Numbers)':Number,
        'Maternity Home Doctors-In Position (Numbers)':Number,
        'Maternity Home Para Medical Staff-Total Strength (Numbers)':Number,
        'Maternity Home Para Medical Staff-In position (Numbers)':Number,
        'Maternity Home Nearest facility Distance (in kms.)':Number,
        'T.B. Hospital/ Clinic (Numbers)':Number,
        'T.B. Hospital/ Clinic Beds (Numbers)':Number,
        'T.B. Hospital/ Clinic Doctors-Total Strength (Numbers)':Number,
        'T.B. Hospital/ Clinic Doctors-In Position (Numbers)':Number,
        'T.B. Hospital/Clinic Para Medical Staff-Total Strength (Numbers)':Number,
        'T.B. Hospital/Clinic Para Medical Staff-In position (Numbers)':Number,
        'T.B. Hospital/ Clinic Nearest facility Distance (in kms.)':Number,
        'Nursing Home (Numbers)' :Number,
        'Nursing Home Beds (Numbers)':Number,
        'Nursing Home Doctors-Total Strength (Numbers)':Number,
        'Nursing Home Doctor-In Postion (Numbers)':Number,
        'Nursing Home Para Medical Staff-Total Strength (Numbers)':Number,
        'Nursing Home Para Medical Staff-In Position (Numbers)':Number,
        'Nursing Home Nearest facility Distance (in kms.)':Number,
        'Veterinary Hospital (Numbers)':Number,
        'Veterinary Hospital Beds (Numbers)':Number,
        'Veterinary Hospital Doctors-Total Strength (Numbers)':Number,
        'Veterinary Hospital Doctors-In Position (Numbers)':Number,
        'Veterinary Hospital Para Medical Staff-Total Strength (Numbers)':Number,
        'Veterinary Hospital Para Medical Staff-In Position (Numbers)':Number,
        'Veterinary Hospital Nearest facility Distance (in kms.)': Number,
        'Mobile Health Clinic (Numbers)':Number,
        'Mobile Health Clinic Beds (Numbers)':Number,
        'Mobile Health Clinic Doctors-Total Strength (Numbers)':Number,
        'Mobile Health Clinic Doctors-In Postion (Numbers)':Number,
        'Mobile Health Clinic Para Medical Staff-Total Strength (Numbers)':Number,
        'Mobile Health Clinic Para Medical Staff-In poistion (Numbers)':Number,
        'Mobile Health Clinic Nearest facility Distance (in kms.)':Number,
        'Others (Numbers)':Number,
        'Others Beds (Numbes)':Number,
        'Others Doctors-Total Strength (Numbers)':Number,
        'Others Doctors-In Position (Numbers)':Number,
        'Others Para Medical Staff-Total Strength (Numbers)':Number,
        'Others Para Medical Staff-In Position (Numbers)':Number,
        'Others Nearest facility Distance (in kms.)':Number,
        'Non-Government Out-Patient (Numbers)':Number,
        'Non-Government In and Out Patient (Numbers)':Number,
        'Non-Government Charitable-Hospital/Nursing Home (Numbers)':Number,
        'Non-Government Medicine Shop (Numbers)':Number,
});
const ShapefilesDB = mongoose.connection.useDb('Shapefiles');
module.exports = ShapefilesDB.model('Town',town_schema);