const mongoose = require('mongoose');

const POI_schema = new mongoose.Schema({
coordinates: Array,
accounting: Number,
airport:Number,
amusement_park:Number,
aquarium:Number,
art_gallery:Number,
atm:Number,
bakery:Number,
bank:Number,
bar: Number,                                                                    
beauty_salon: Number,                                                                           
bicycle_store: Number,                                                                     
book_store:Number,                                                           
bowling_alley:Number,                                                                            
bus_station:Number,                                                                            
cafe:  Number,                                                                        
campground: Number,                                                                          
car_dealer: Number,                                                                           
car_rental: Number,                                                                           
car_repair: Number,                                                                           
car_wash: Number,                                                                           
casino: Number,                                                                           
cemetery: Number,                                                                           
church:  Number,                                                                          
city_hall:Number,                                                                            
clothing_store: Number,                                                                           
convenience_store:  Number,                                                                          
courthouse:Number,                                                                            
dentist: Number,                                                                           
department_store:Number,                                                                            
doctor: Number,                                                                           
electrician: Number,                                                                           
electronics_store:  Number,                                                                          
embassy: Number,                                                                           
fire_station:   Number,                                                                         
florist: Number,                                                                           
funeral_home: Number,                                                                           
furniture_store: Number,                                                                           
gas_station: Number,                                                                           
gym:Number,                                                                            
hair_care: Number,                                                                           
hardware_store:Number,                                                                            
hindu_temple: Number,                                                                           
home_goods_store:Number,                                                                            
hospital:Number,                                                                            
insurance_agency: Number,                                                                           
jewelry_store:Number,                                                                            
laundry:  Number,                                                                          
lawyer:  Number,                                                                          
library: Number,                                                                           
liquor_store:Number,                                                                            
local_government_office: Number,                                                                           
locksmith:Number,                                                                            
lodging:  Number,                                                                          
meal_delivery:Number,                                                                            
meal_takeaway:Number,                                                                            
mosque:Number,                                                                            
movie_rental: Number,                                                                           
movie_theater:Number,                                                                            
moving_company: Number,                                                                           
museum: Number,                                                                           
night_club:Number,                                                                            
painter: Number,                                                                           
park: Number,                                                                           
parking: Number,                                                                           
pet_store: Number,                                                                           
pharmacy:  Number,                                                                          
physiotherapist: Number,                                                                           
plumber: Number,                                                                           
police:   Number,                                                                         
post_office:   Number,                                                                         
real_estate_agency:   Number,                                                                         
restaurant:  Number,                                                                          
roofing_contractor: Number,                                                                           
rv_park: Number,                                                                           
school:  Number,                                                                          
shoe_store: Number,                                                                           
shopping_mall: Number,                                                                           
spa: Number,                                                                           
stadium:    Number,                                                                        
storage: Number,                                                                           
store: Number,                                                                           
subway_station: Number,                                                                           
supermarket: Number,                                                                           
synagogue:   Number,                                                                         
taxi_stand:  Number,                                                                          
train_station: Number,                                                                           
transit_station: Number,                                                                           
travel_agency: Number,                                                                           
veterinary_care: Number,                                                                           
zoo: Number,                                                                           
administrative_area_level_1:Number,                                                                            
administrative_area_level_2:Number,                                                                            
administrative_area_level_3:Number,                                                                            
administrative_area_level_4:Number,                                                                            
administrative_area_level_5:Number,                                                                            
colloquial_area:Number,                                                                            
country:Number,                                                                            
establishment: Number,                                                                           
finance:Number,                                                                            
floor:Number,                                                                            
food: Number,                                                                           
general_contractor:Number,                                                                            
geocode:Number,                                                                            
health: Number,                                                                           
intersection: Number,                                                                           
locality: Number,                                                                           
natural_feature: Number,                                                                           
neighborhood: Number,                                                                           
place_of_worship: Number,                                                                           
political: Number,                                                                           
point_of_interest:Number,                                                                            
post_box: Number,                                                                           
postal_code:     Number,                                                                       
postal_code_prefix:     Number,                                                                       
postal_code_suffix:   Number,                                                                         
postal_town:  Number,                                                                          
premise: Number,                                                                           
room:   Number,                                                                         
route:  Number,                                                                          
street_address: Number,                                                                           
street_number: Number,                                                                   
sublocality:Number,                                                          
sublocality_level_4:Number,                                                           
sublocality_level_5:Number,                                                                            
sublocality_level_3:Number,                                                                            
sublocality_level_2:Number,                                                                            
sublocality_level_1:Number,                                                                            
subpremise:Number,
},{collection : 'POI'  })
module.exports = mongoose.model('POI',POI_schema);